package app.cotizador.model;
// Generated 05-feb-2021 6:19:28 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * DatosVehiculo generated by hbm2java
 */
@Entity
@Table(name = "datos_vehiculo", schema = "dbo", catalog = "db_cotizador")
@XmlRootElement
public class DatosVehiculo implements java.io.Serializable {

	private long valorizacionId;
	private Marca marca;
	private Modelo modelo;
	private Integer ano;
	private Character estado;
	private Character uso;
	private Integer modeloId;

	public DatosVehiculo() {
	}

	public DatosVehiculo(long valorizacionId) {
		this.valorizacionId = valorizacionId;
	}
	public DatosVehiculo(long valorizacionId, Marca marca, Modelo modelo,
			Integer ano, Character estado, Character uso, Integer modeloId) {
		this.valorizacionId = valorizacionId;
		this.marca = marca;
		this.modelo = modelo;
		this.ano = ano;
		this.estado = estado;
		this.uso = uso;
		this.modeloId = modeloId;
	}

	@Id
	@Column(name = "valorizacion_id", unique = true, nullable = false)
	public long getValorizacionId() {
		return this.valorizacionId;
	}

	public void setValorizacionId(long valorizacionId) {
		this.valorizacionId = valorizacionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "marca")
	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modelo")
	public Modelo getModelo() {
		return this.modelo;
	}

	public void setModelo(Modelo modelo) {
		this.modelo = modelo;
	}

	@Column(name = "ano")
	public Integer getAno() {
		return this.ano;
	}

	public void setAno(Integer ano) {
		this.ano = ano;
	}

	@Column(name = "estado", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Column(name = "uso", length = 1)
	public Character getUso() {
		return this.uso;
	}

	public void setUso(Character uso) {
		this.uso = uso;
	}

	@Column(name = "modelo_id")
	public Integer getModeloId() {
		return this.modeloId;
	}

	public void setModeloId(Integer modeloId) {
		this.modeloId = modeloId;
	}

}
