package app.cotizador.model;
// Generated 05-feb-2021 6:19:28 by Hibernate Tools 5.2.11.Final

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Marca generated by hbm2java
 */
@Entity
@Table(name = "marca", schema = "dbo", catalog = "db_cotizador")
@XmlRootElement
public class Marca implements java.io.Serializable {

	private Integer marcaId;
	private String descripcion;
	private List<Modelo> modelos = new ArrayList<Modelo>();
	//private Set<DatosVehiculo> datosVehiculos = new HashSet<DatosVehiculo>(0);

	public Marca() {
	}

	public Marca(Integer marcaId) {
		this.marcaId = marcaId;
	}
	public Marca(int marcaId, String descripcion, Set<Modelo> modelos,
			Set<DatosVehiculo> datosVehiculos) {
		this.marcaId = marcaId;
		this.descripcion = descripcion;
		
	//	this.datosVehiculos = datosVehiculos;
	}

	@Id
	@Column(name = "marca_id", unique = true, nullable = false)
	public Integer getMarcaId() {
		return this.marcaId;
	}

	public void setMarcaId(Integer marcaId) {
		this.marcaId = marcaId;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marca")
	public List<Modelo> getModelos() {
		return this.modelos;
	}

	public void setModelos(List<Modelo> modelos) {
		this.modelos = modelos;
	}

	
}
