package app.cotizador.model;
// Generated 05-feb-2021 6:19:28 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name = "modelo", schema = "dbo", catalog = "db_cotizador")
@XmlRootElement
public class Modelo implements java.io.Serializable {

	private Long id;
	private Marca marca;
	private String descripcion;
	private Integer modeloId;

	public Modelo() {
	}

	public Modelo(long id) {
		this.id = id;
	}
	public Modelo(long id, Marca marca, String descripcion, Integer modeloId,
			Set<DatosVehiculo> datosVehiculos) {
		this.id = id;
		this.marca = marca;
		this.descripcion = descripcion;
		this.modeloId = modeloId;
		//this.datosVehiculos = datosVehiculos;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 15, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "marca_id")
	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "modelo_id")
	public Integer getModeloId() {
		return this.modeloId;
	}

	public void setModeloId(Integer modeloId) {
		this.modeloId = modeloId;
	}

}
