package app.cotizador.model;
// Generated 05-feb-2021 6:19:28 by Hibernate Tools 5.2.11.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * ResultadoValorizacion generated by hbm2java
 */
@Entity
@Table(name = "resultado_valorizacion", schema = "dbo", catalog = "db_cotizador")
@XmlRootElement
public class ResultadoValorizacion implements java.io.Serializable {

	private BigDecimal resultadoId;
	private Long valorizacionId;
	private int planId;
	private String compania;
	private String logo;
	private String planDeCobertura;
	private String nemotecnico;
	private int deducible;
	private BigDecimal valor;
	private int estado;
	private String grupo;
	private String subgrupo;
	private String subgrupoAbrev;
	private String mensajeError;

	public ResultadoValorizacion() {
	}

	public ResultadoValorizacion(BigDecimal resultadoId, int planId,
			String compania, String planDeCobertura, String nemotecnico,
			int deducible, BigDecimal valor, int estado) {
		this.resultadoId = resultadoId;
		this.planId = planId;
		this.compania = compania;
		this.planDeCobertura = planDeCobertura;
		this.nemotecnico = nemotecnico;
		this.deducible = deducible;
		this.valor = valor;
		this.estado = estado;
	}
	public ResultadoValorizacion(BigDecimal resultadoId, Long valorizacionId,
			int planId, String compania, String logo, String planDeCobertura,
			String nemotecnico, int deducible, BigDecimal valor, int estado,
			String grupo, String subgrupo, String subgrupoAbrev,
			String mensajeError) {
		this.resultadoId = resultadoId;
		this.valorizacionId = valorizacionId;
		this.planId = planId;
		this.compania = compania;
		this.logo = logo;
		this.planDeCobertura = planDeCobertura;
		this.nemotecnico = nemotecnico;
		this.deducible = deducible;
		this.valor = valor;
		this.estado = estado;
		this.grupo = grupo;
		this.subgrupo = subgrupo;
		this.subgrupoAbrev = subgrupoAbrev;
		this.mensajeError = mensajeError;
	}

	@Id
	@Column(name = "resultado_id", unique = true, nullable = false, precision = 20, scale = 0)
	public BigDecimal getResultadoId() {
		return this.resultadoId;
	}

	public void setResultadoId(BigDecimal resultadoId) {
		this.resultadoId = resultadoId;
	}

	@Column(name = "valorizacion_id")
	public Long getValorizacionId() {
		return this.valorizacionId;
	}

	public void setValorizacionId(Long valorizacionId) {
		this.valorizacionId = valorizacionId;
	}

	@Column(name = "plan_id", nullable = false)
	public int getPlanId() {
		return this.planId;
	}

	public void setPlanId(int planId) {
		this.planId = planId;
	}

	@Column(name = "compania", nullable = false, length = 100)
	public String getCompania() {
		return this.compania;
	}

	public void setCompania(String compania) {
		this.compania = compania;
	}

	@Column(name = "logo", length = 100)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "plan_de_cobertura", nullable = false, length = 100)
	public String getPlanDeCobertura() {
		return this.planDeCobertura;
	}

	public void setPlanDeCobertura(String planDeCobertura) {
		this.planDeCobertura = planDeCobertura;
	}

	@Column(name = "nemotecnico", nullable = false, length = 6)
	public String getNemotecnico() {
		return this.nemotecnico;
	}

	public void setNemotecnico(String nemotecnico) {
		this.nemotecnico = nemotecnico;
	}

	@Column(name = "deducible", nullable = false)
	public int getDeducible() {
		return this.deducible;
	}

	public void setDeducible(int deducible) {
		this.deducible = deducible;
	}

	@Column(name = "valor", nullable = false, precision = 5, scale = 4)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	@Column(name = "grupo", length = 100)
	public String getGrupo() {
		return this.grupo;
	}

	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	@Column(name = "subgrupo", length = 100)
	public String getSubgrupo() {
		return this.subgrupo;
	}

	public void setSubgrupo(String subgrupo) {
		this.subgrupo = subgrupo;
	}

	@Column(name = "subgrupo_abrev", length = 10)
	public String getSubgrupoAbrev() {
		return this.subgrupoAbrev;
	}

	public void setSubgrupoAbrev(String subgrupoAbrev) {
		this.subgrupoAbrev = subgrupoAbrev;
	}

	@Column(name = "mensaje_error", length = 300)
	public String getMensajeError() {
		return this.mensajeError;
	}

	public void setMensajeError(String mensajeError) {
		this.mensajeError = mensajeError;
	}

}
