package app.cotizador.model;
// Generated 05-feb-2021 7:00:47 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Valorizacion generated by hbm2java
 */
@Entity
@Table(name = "valorizacion", schema = "dbo", catalog = "db_cotizador")
@XmlRootElement
public class Valorizacion implements java.io.Serializable {

	private Long valorizacionId;
	private EstadoValorizacion estadoValorizacion;
	private Integer usuarioId;
	private Long rut;
	private Date fecha;
	private Date fechaHora;
	private boolean clienteNuevo;

	public Valorizacion() {
	}

	public Valorizacion(boolean clienteNuevo) {
		this.clienteNuevo = clienteNuevo;
	}
	public Valorizacion(EstadoValorizacion estadoValorizacion,
			Integer usuarioId, Long rut, Date fecha, Date fechaHora,
			boolean clienteNuevo) {
		this.estadoValorizacion = estadoValorizacion;
		this.usuarioId = usuarioId;
		this.rut = rut;
		this.fecha = fecha;
		this.fechaHora = fechaHora;
		this.clienteNuevo = clienteNuevo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "valorizacion_id", unique = true, nullable = false)
	public Long getValorizacionId() {
		return this.valorizacionId;
	}

	public void setValorizacionId(Long valorizacionId) {
		this.valorizacionId = valorizacionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estado")
	public EstadoValorizacion getEstadoValorizacion() {
		return this.estadoValorizacion;
	}

	public void setEstadoValorizacion(EstadoValorizacion estadoValorizacion) {
		this.estadoValorizacion = estadoValorizacion;
	}

	@Column(name = "usuario_id")
	public Integer getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(Integer usuarioId) {
		this.usuarioId = usuarioId;
	}

	@Column(name = "rut", precision = 10, scale = 0)
	public Long getRut() {
		return this.rut;
	}

	public void setRut(Long rut) {
		this.rut = rut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_hora", length = 23)
	public Date getFechaHora() {
		return this.fechaHora;
	}

	public void setFechaHora(Date fechaHora) {
		this.fechaHora = fechaHora;
	}

	@Column(name = "cliente_nuevo", nullable = false)
	public boolean isClienteNuevo() {
		return this.clienteNuevo;
	}

	public void setClienteNuevo(boolean clienteNuevo) {
		this.clienteNuevo = clienteNuevo;
	}

}
